### PR TITLE
Initial checkin of ar6002 driver from atheros SDK83

### PR DESCRIPTION
**Pull request by dzenc**
Includes driver revision 2.2.1.83, ported to work with the stock Radio wifi firmware revision 2.1.2.62.

Several changes have been made which attempt to improve the stability of wifi connectivity, with the most impactful being to remove "/lib/atheros/wmiconfig -eth1 --power maxperf" from the /etc/init.d/wlan script, resulting in signficantly improved stability for some users.

Detailed changes:

* update checksums.ini to include http://ralph.irving.sdf.org/squeezeos/atheros-ar6ksdk.build_sw.83.tar.gz

* add new recipe poky/meta-squeezeos/packages/atheros/atheros-ar6-module-src_1.1.bb

* add baseline patches from ralph-irving to support driver on Radio
	* AR6kSDK.build_sw.83.baby.patch
	* atheros_configpm.patch
	* atheros_nostatupdate.patch
	* BMI_read_mem_failure.patch
	* change-ar6k-semaphore-type.patch

* additional patches as described below:
	* 0001-enable-debug-output.patch - enable debugging output in ar6000_drv.h
	* 0002-too-short-debug.patch - add additional debug output for "TOO SHORT" log message
	* 0003-driver-print-version.patch - log driver version on startup
	* 0004-backport-old-ioctl-target-stats.patch - provide compatibility with existing user space tools by adjusting ioctl structures
	* 0005-support-old-and-new-firmware-target-stats.patch - provide compatibility with the target stats structure returned by both the old and new firmware versions
	* 0006-backport-old-ioctl-wmiconfig.patch - provide compatibility with existing user space tools by adjusting ioctl id's
	* 0007-log-power-setting.patch - add additional debug logging for wifi power setting (maxperf vs rec)
	* 0008-log-phy-rate-change.patch - add additional debug logging for wifi phy rate change (e.g. gonly mode)
	* 0009-arp-dhcp-logging.patch - add support for runtime enable/disable of additional arp and dhcp tracing

* add user visible configuration applet for configuring wifi robustness features (appears in Settings/Advanced/Networking/Wifi Robustness Options) * SetupWifiRobustness/SetupWifiRobustnessApplet.lua * SetupWifiRobustness/SetupWifiRobustnessMeta.lua * SetupWifiRobustness/strings.txt

        Two configurable settings are offered to the user:
        	"Enable ARP watchdog" and "Disable legacy 802.11b"
        	Both are disabled by default and controlled by settings in /etc/wlan.conf

* add /lib/atheros/restart-wifi.sh script, which is used to restart the wifi stack

* add /lib/atheros/watch-arp.sh script, which, when enabled, is used to monitor the ARP cache and reset the wifi stack if needed

* update /etc/init.d/wlan script
	* remove maxperf (resulting in the default 'rec' power setting)
	* add support for optional gonly mode, optional ARP watchdog script (both configured by /etc/wlan.conf)

	<       # Temporary possible work-a-round to fix wireless connectivity issues
	<       # Disable power save mode
	<       /lib/atheros/wmiconfig -eth1 --power maxperf
	---
	>       # act on settings from /etc/wlan.conf
	>       if [ "${gonly}" == "on" ]; then
	>               /lib/atheros/wmiconfig --wmode gonly
	>       fi
	>
	>       if [ "${arpwatch}" == "on" ]; then
	>               /lib/atheros/watch-arp.sh
	>       fi

### CODE REVIEW

**Comment by ralph-irving** [comment]
Could you add these missing files from your atheros-ar6-module-src-1.1 folder?

athwlan.bin
wmiconfig
eeprom.AR6002
data.patch.hw2_0.bin
calData_ar6102_15dBm.bin
bmiloader
loadAR6000l.sh

I'd like to be sure we are using the same files that were used for your test builds in the release.
Thanks.

**Comment by dzenc** [comment]
These are automatically pulled from the “files” directory.  So the files are already there.   There is no need to put them in atheros-ar6-module-src-1.1.

And this is the same as my test build.  :)

(There is no need for a second copy because these files are the same as the ones that come with the binary build.)

**Comment by ralph-irving** [comment]
I have 2 versions of data.patch.hw2_0.bin which one did you use?
atheros/files/data.patch.hw2_0.bin size 836
atheros/atheros-ar6-module-src-1.1/data.patch.hw2_0.bin size 1336

EDIT: The one in my atheros-ar6-module-src-1.1 is from the first build I created with SDK83, I've removed it.

**Comment by dzenc** [comment]
The one from “files”.   (again, you shouldn’t need to check one in.  It should just pick up the one that’s already checked in automatically.  I double checked and everything in my atheros directory is in the pull request.  If you are having trouble building it as-is, please let me know.)

**Pull request merged**
